### ISSUE TITLE
Failed to compile with 2 errors 

### ISSUE THREAD

**Issue by liumapp** [kkeisuke/plantuml-editor#2]
ERROR  Failed to compile with 2 errors                                                                                                09:44:01

 one is   in ./src/components/Editor.vue (Module build failed: TypeError: Cannot read property 'type' of undefined)

 the next error  in ./src/directive/modules/clipboard.js(Module build failed: TypeError: Cannot read property 'type' of undefined)

and the page look like this  ![1 pic](https://user-images.githubusercontent.com/21333655/35021293-3691c720-fb6b-11e7-81d4-4b2245a62d69.jpg) . 

my node version is 9.4.0 and npm version is 5.6.0

**Comment by kkeisuke** [comment]
I tried with the same version of my Node.js and npm, but it did not reproduce.
Have you noticed anything else?

**Comment by liumapp** [comment]
I copied the whole error info below : 

ERROR  Failed to compile with 1 errors                                                                                                              23:00:48

 error  in ./src/directive/modules/clipboard.js

Module build failed: TypeError: Cannot read property 'type' of undefined
    at hasTypeOfOperator (/usr/local/tomcat/project/plantuml-editor/node_modules/_eslint@4.16.0@eslint/lib/rules/no-undef.js:19:19)
    at Program:exit.globalScope.through.forEach.ref (/usr/local/tomcat/project/plantuml-editor/node_modules/_eslint@4.16.0@eslint/lib/rules/no-undef.js:59:44)
    at Array.forEach (<anonymous>)
    at Program:exit (/usr/local/tomcat/project/plantuml-editor/node_modules/_eslint@4.16.0@eslint/lib/rules/no-undef.js:56:37)
    at listeners.(anonymous function).forEach.listener (/usr/local/tomcat/project/plantuml-editor/node_modules/_eslint@4.16.0@eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/usr/local/tomcat/project/plantuml-editor/node_modules/_eslint@4.16.0@eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/usr/local/tomcat/project/plantuml-editor/node_modules/_eslint@4.16.0@eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/usr/local/tomcat/project/plantuml-editor/node_modules/_eslint@4.16.0@eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.leaveNode (/usr/local/tomcat/project/plantuml-editor/node_modules/_eslint@4.16.0@eslint/lib/util/node-event-generator.js:303:14)
    at CodePathAnalyzer.leaveNode (/usr/local/tomcat/project/plantuml-editor/node_modules/_eslint@4.16.0@eslint/lib/code-path-analysis/code-path-analyzer.js:630:23)
    at Traverser.leave [as _leave] (/usr/local/tomcat/project/plantuml-editor/node_modules/_eslint@4.16.0@eslint/lib/linter.js:1009:32)
    at Traverser._traverse (/usr/local/tomcat/project/plantuml-editor/node_modules/_eslint@4.16.0@eslint/lib/util/traverser.js:155:18)
    at Traverser.traverse (/usr/local/tomcat/project/plantuml-editor/node_modules/_eslint@4.16.0@eslint/lib/util/traverser.js:115:14)
    at Linter._verifyWithoutProcessors (/usr/local/tomcat/project/plantuml-editor/node_modules/_eslint@4.16.0@eslint/lib/linter.js:1003:19)
    at preprocess.map.textBlock (/usr/local/tomcat/project/plantuml-editor/node_modules/_eslint@4.16.0@eslint/lib/linter.js:1045:35)
    at Array.map (<anonymous>)
    at Linter.verify (/usr/local/tomcat/project/plantuml-editor/node_modules/_eslint@4.16.0@eslint/lib/linter.js:1044:42)
    at localVerify (/usr/local/tomcat/project/plantuml-editor/node_modules/_eslint-plugin-html@4.0.1@eslint-plugin-html/src/index.js:81:14)
    at Linter.verify (/usr/local/tomcat/project/plantuml-editor/node_modules/_eslint-plugin-html@4.0.1@eslint-plugin-html/src/index.js:145:18)
    at Linter.verifyAndFix (/usr/local/tomcat/project/plantuml-editor/node_modules/_eslint@4.16.0@eslint/lib/linter.js:1136:29)
    at processText (/usr/local/tomcat/project/plantuml-editor/node_modules/_eslint@4.16.0@eslint/lib/cli-engine.js:179:32)

 @ ./src/directive/index.js 8:0-44
 @ ./~/_babel-loader@6.4.1@babel-loader/lib!./~/_vue-loader@13.5.0@vue-loader/lib/selector.js?type=script&index=0&bustCache!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

> Listening at http://localhost:8080

**Comment by kkeisuke** [comment]
Please try the following procedure

1. delete `./node_modules` folder
2. revert changes
2. npm install
3. npm run dev

Has your `package-lock.json` file changed?

**Comment by liumapp** [comment]
Now it works ...
But there is one question . 
My ip address belong to China , the main land , which makes it hard to acquire some resources .
I solved this problem by using Lantern , so , it shall be helpful for the others if you mention this in README.md .

**Comment by kkeisuke** [comment]
This application uses heroku for PlantUML server.
it takes time to start up, because it uses free plan of heroku.
I'm considering features that allow you to set up your own PlantUML server.
Please wait for a little while.
